version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: sales-intel-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
